layout_spectrum: 0.7404255
typography_spectrum: 0.9893617
color:
  saturation: 0.4106383
  lightness: 0.7297872
  brandStrength: 0.266666
  brandColors:
    - '#E3120B'
    - '#DFDFDF'
    - '#343432'
    - '#E6524F'
    - '#808080'
  rhythmicContrast: 0.4851064
name: The Economist
